apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: jenkins-ns
spec:
  selector:
    app: jenkins
  ports:
  - port: 8080
    targetPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: jenkins-agent
  namespace: jenkins-ns
spec:
  selector:
    app: jenkins
  ports:
  - port: 50000
    targetPort: 50000