---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-maven-repo
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: retained
  resources:
    requests:
      storage: 10Gi